In [4]:
import numpy as np

an_array = np.array([[0,1,2,3,4] , [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19]])

green = an_array[0,1:]
blue = an_array[1:3,:]

print("Green")
print(green)
print("Blue")
print(blue)

Green
[1 2 3 4]
Blue
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
an_array = np.array([[0,1,2,3,4] , [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19]])

red = an_array[::3,::2]
print("Red")
print(red)

Red
[[ 0  2  4]
 [15 17 19]]


In [6]:
an_array = np.array([[111,222],[333,444],[555,666]])

even_filter = (an_array >= 200) & (an_array <= 400) & (an_array % 2 == 0)

print('filter')
print(even_filter)

filter
[[False  True]
 [False False]
 [False False]]


In [8]:
an_array = np.random.normal(100,.2,(2,3,4))

print(an_array)

[[[ 99.96956736 100.13437551 100.29637779 100.0346634 ]
  [100.17809974 100.19126336  99.80368115 100.32476651]
  [ 99.77311277  99.58230747  99.68143769  99.83510369]]

 [[100.03895788  99.64704797  99.96023745 100.24115339]
  [ 99.99267855 100.16060218 100.15584311  99.88632208]
  [ 99.93529467 100.26699515 100.2390287  100.03083069]]]


In [9]:
array1 = np.array(['apple','banana','grape'])
array2 = np.array(['apple','orange','grape'])
array3 = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

print(np.in1d(array1,array2))
print(np.intersect1d(array1,array2))
print(np.setdiff1d(array1,array2))
print(np.union1d(array1,array2))
print(np.unique(array3))

[ True False  True]
['apple' 'grape']
['banana']
['apple' 'banana' 'grape' 'orange']
[1 2 3 4 5 6]


In [11]:
np_array = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]]) 

print('sum by row')
print(np_array.sum(axis = 1))

print('sum by column')
print(np_array.sum(axis=0))

sum by row
[[12 15 18 21]
 [48 51 54 57]]
sum by column
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
